name: Scrape latest data

on:
  schedule:
    - cron:  '14 2 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run scraper
      run: bundle exec ruby scraper.rb | tee data.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add data.csv
        timestamp=$(date -u)
        git commit -m "Update data: ${timestamp}" || exit 0
        git push
